_target_: src.models.pvnet_module.PVNetLitModule
lr: 1e-3
weight_decay: 0.0
milestones: [20, 40, 60, 80, 100, 120, 160, 180, 200, 220]
gamma: 0.5
un_pnp: False

net:
  _target_: src.models.pvnet.pvnet.Resnet18
  ver_dim: 18
  seg_dim: 2
  pretrained_path: '${original_work_dir}/logs/PVNet-Model/${obj_cls}_199.pth'
